### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by AwesomeLemon** [ellbur/totalmapper#2] opened 2021-05-24 16:56 UTC
Hi,

Firstly, really like the idea of the tool. Unfortunately, it fails for me.
I'm on Ubuntu 20.04. I've built the project from the source. It appears to have succeeded: I can run ``totalmapper``
However, when I run ``sudo totalmapper remap --default-layout caps-for-movement --all-keyboards``, a lot of empty lines are outputted into the terminal and the mouse cursor stops responding. I tried it for a couple of times, waiting no longer than 10 seconds, because I'm wary that something could get broken. But I saw no effect, adverse or otherwise.

Could you give some advice on what I should try?

**Comment by AwesomeLemon** [comment] 2021-05-24 17:23
I investigated the issue further and was able to work around it.
The problem apparently was caused by the " --all-keyboards" part: although I have a single laptop keyboard, list_keyboard gave me a lot of options:
```
/dev/input/event2
/dev/input/event8
/dev/input/event9
/dev/input/event10
/dev/input/event12
/dev/input/event6
```
By running ``cat /proc/bus/input/devices  | grep -P '^[NH]: ' | paste - -`` I was able to figure out what is what. Apparently, one of those things was my mouse - that explains why it froze. 
My keyboard is event2, so running ``sudo totalmapper remap --layout-file my-layout.json --dev-file /dev/input/event2`` works fine, except for the billion new lines in the terminal, but those could be redirected. Still, I think it'd be interesting to know what caused them. 
In any case, everything works now (even in Sublime and Pycharm), I'm very happy, thanks for writing this program! 
I'd be glad to help you figure out what's going awry, but also feel free to just close the issue

**Comment by AwesomeLemon** [comment] 2021-05-24 17:29
Since it never stops executing, I added it to my .bashrc like so: ``sudo totalmapper remap --layout-file my-layout.json --dev-file /dev/input/event2 2> /dev/null &``
Registering as a service doesn't seem to work because I can't pass the dev file to it

**Comment by ellbur** [comment] 2021-05-24 20:19
Hi @AwesomeLemon,

Thank you for providing your thorough investigation of these issues. It is very helpful.

Regarding the blank lines that get printed to a terminal: those are actually caused by pressing the <kbd>Enter</kbd> key when you run the command. This is an issue I don't know how fix correctly: you press the <kbd>Enter</kbd> key on your real keyboard, then `totalmapper` disables your real keyboard, then you release the <kbd>Enter</kbd> key---but the release gets swallowed. 

A workaround is to run `sleep` to give you time to release <kbd>Enter</kbd>:

    sleep 1 ; sudo totalmapper remap --layout-file my-layout.json --dev-file /dev/input/event2

It also works if you run `totalmapper` from a startup script, as you do; that way, there's no <kbd>Enter</kbd> to worry about.

Regarding detecting your mouse as a keyboard: this is another issue I've had to tweak over time, and it seems it still needs some tweaking. On Linux, there's no hard line between a "keyboard" and other input devices like a mouse, lid switch, or power button. They are all input devices, with varying numbers of "keys". Clearly the way I am trying to distinguish keyboards from mice is not working. 

If you get a chance, could you post the output of `cat /proc/bus/input/devices`? That will give me an idea how to distinguish your mouse from a keyboard.

**Comment by AwesomeLemon** [comment] 2021-05-25 10:19
Hi,

As a suggestion about the ``Enter`` problem: couldn't you programmatically release the key? (e.g. in python I'd try something like ``Controller().release('Enter')``)

Here's the output of ``cat /proc/bus/input/devices``:
```
I: Bus=0019 Vendor=0000 Product=0005 Version=0000
N: Name="Lid Switch"
P: Phys=PNP0C0D/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input0
U: Uniq=
H: Handlers=event0 
B: PROP=0
B: EV=21
B: SW=1

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0011 Vendor=0001 Product=0001 Version=ab41
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input2
U: Uniq=
H: Handlers=sysrq kbd event2 leds 
B: PROP=0
B: EV=120013
B: KEY=1100f02902000 8380307cf910f001 feffffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input5
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0011 Vendor=0002 Product=0001 Version=0000
N: Name="PS/2 Generic Mouse"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input4
U: Uniq=
H: Handlers=mouse3 event7 
B: PROP=1
B: EV=7
B: KEY=70000 0 0 0 0
B: REL=3

I: Bus=0003 Vendor=0c76 Product=161e Version=0100
N: Name="USB PnP Audio Device"
P: Phys=usb-0000:00:14.0-2/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.2/0003:0C76:161E.0004/input/input11
U: Uniq=
H: Handlers=kbd event8 
B: PROP=0
B: EV=13
B: KEY=7800000000 e000000000000 0
B: MSC=10

I: Bus=0003 Vendor=145f Product=01bc Version=0110
N: Name="GXT 4155 Gaming Mouse"
P: Phys=usb-0000:00:14.0-1.3/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.0/0003:145F:01BC.0005/input/input12
U: Uniq=
H: Handlers=mouse4 event9 
B: PROP=0
B: EV=17
B: KEY=ffff0000 0 0 0 0
B: REL=1943
B: MSC=10

I: Bus=0003 Vendor=145f Product=01bc Version=0110
N: Name="GXT 4155 Gaming Mouse"
P: Phys=usb-0000:00:14.0-1.3/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.1/0003:145F:01BC.0006/input/input13
U: Uniq=
H: Handlers=sysrq kbd event10 
B: PROP=0
B: EV=100013
B: KEY=1000000000007 ff9f207ac14057ff febeffdfffefffff fffffffffffffffe
B: MSC=10

I: Bus=0003 Vendor=145f Product=01bc Version=0110
N: Name="GXT 4155 Gaming Mouse Consumer Control"
P: Phys=usb-0000:00:14.0-1.3/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.2/0003:145F:01BC.0007/input/input14
U: Uniq=
H: Handlers=kbd event11 
B: PROP=0
B: EV=1f
B: KEY=3f000301ff 0 0 483ffff17aff32d bfd4444600000000 1 130ff38b17c000 677bfad9415fed 19ed68000004400 10000002
B: REL=1040
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=145f Product=01bc Version=0110
N: Name="GXT 4155 Gaming Mouse"
P: Phys=usb-0000:00:14.0-1.3/input2
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1.3/1-1.3:1.2/0003:145F:01BC.0007/input/input15
U: Uniq=
H: Handlers=event12 
B: PROP=0
B: EV=9
B: ABS=10000000000

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Intel HID events"
P: Phys=
S: Sysfs=/devices/platform/INT33D5:00/input/input16
U: Uniq=
H: Handlers=rfkill kbd event13 
B: PROP=0
B: EV=13
B: KEY=81000300000000 5000004000 1e294000000020 0
B: MSC=10

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Intel HID 5 button array"
P: Phys=
S: Sysfs=/devices/platform/INT33D5:00/input/input17
U: Uniq=
H: Handlers=kbd event14 
B: PROP=0
B: EV=13
B: KEY=2000000000000 0 0 0 0 1000000000000 0 201c000000000000 0
B: MSC=10

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Dell WMI hotkeys"
P: Phys=
S: Sysfs=/devices/platform/PNP0C14:03/wmi_bus/wmi_bus-PNP0C14:03/9DBB5994-A997-11DA-B012-B622A1EF5492/input/input18
U: Uniq=
H: Handlers=rfkill kbd event4 
B: PROP=0
B: EV=13
B: KEY=800000000000 0 0 1500b00000c00 4000001200300000 e000000000000 0
B: MSC=10

I: Bus=0018 Vendor=27c6 Product=01e0 Version=0100
N: Name="DELL09EC:00 27C6:01E0 Mouse"
P: Phys=i2c-DELL09EC:00
S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-DELL09EC:00/0018:27C6:01E0.0001/input/input19
U: Uniq=
H: Handlers=mouse0 event5 
B: PROP=0
B: EV=17
B: KEY=30000 0 0 0 0
B: REL=1943
B: MSC=10

I: Bus=0018 Vendor=27c6 Product=01e0 Version=0100
N: Name="DELL09EC:00 27C6:01E0 Touchpad"
P: Phys=i2c-DELL09EC:00
S: Sysfs=/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-DELL09EC:00/0018:27C6:01E0.0001/input/input20
U: Uniq=
H: Handlers=mouse1 event15 
B: PROP=5
B: EV=1b
B: KEY=e520 10000 0 0 0 0
B: ABS=2e0800000000003
B: MSC=20

I: Bus=0018 Vendor=1fd2 Product=8002 Version=0100
N: Name="CUST0000:00 1FD2:8002"
P: Phys=i2c-CUST0000:00
S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-8/i2c-CUST0000:00/0018:1FD2:8002.0002/input/input22
U: Uniq=
H: Handlers=mouse2 event6 
B: PROP=2
B: EV=1b
B: KEY=400 0 0 0 0 0
B: ABS=260800000000003
B: MSC=20

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="sof-hda-dsp Headphone Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input24
U: Uniq=
H: Handlers=event16 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="sof-hda-dsp HDMI/DP,pcm=3"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input25
U: Uniq=
H: Handlers=event17 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="sof-hda-dsp HDMI/DP,pcm=4"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input26
U: Uniq=
H: Handlers=event18 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="sof-hda-dsp HDMI/DP,pcm=5"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input27
U: Uniq=
H: Handlers=event19 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0003 Vendor=1bcf Product=2283 Version=1217
N: Name="NexiGo N930AF FHD Webcam: NexiG"
P: Phys=usb-0000:00:14.0-3/button
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/input/input28
U: Uniq=
H: Handlers=kbd event20 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0003 Vendor=0bda Product=5532 Version=8264
N: Name="Integrated_Webcam_HD: Integrate"
P: Phys=usb-0000:00:14.0-6/button
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.0/input/input29
U: Uniq=
H: Handlers=kbd event21 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0003 Vendor=0bda Product=5532 Version=8264
N: Name="Integrated_Webcam_HD: Integrate"
P: Phys=usb-0000:00:14.0-6/button
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.2/input/input30
U: Uniq=
H: Handlers=kbd event22 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0003 Vendor=0001 Product=0001 Version=0001
N: Name="totalmapper"
P: Phys=
S: Sysfs=/devices/virtual/input/input31
U: Uniq=
H: Handlers=sysrq rfkill kbd event23 
B: PROP=0
B: EV=13
B: KEY=3ffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff fffffffffffffffe
B: MSC=0

I: Bus=0005 Vendor=000a Product=ffff Version=ffff
N: Name="TaoTronics TT-BH22 (AVRCP)"
P: Phys=e0:2b:e9:ef:f7:30
S: Sysfs=/devices/virtual/input/input33
U: Uniq=
H: Handlers=kbd event24 
B: PROP=0
B: EV=100007
B: KEY=2fc800 145200000000 0 10300 49e800000c00 e16800000000f f810000010000ffc
B: REL=0
```

**Comment by ellbur** [comment] 2021-05-25 13:21
Thanks for providing that info.

The tricky part about programmatically releasing the key is that keypresses are tracked separately for each keyboard. `totalmapper` works by creating a virtual keyboard and disabling the real one. I can send a key release to the virtual keyboard, but that won't release the key in the real keyboard. 

I think what I'll have to do is check to see if a key is pressed, and, if so, wait for it to be released before disabling the real keyboard. Something along the lines of [this stackoverflow post](https://stackoverflow.com/a/61092344/371739).

I've created separate issues for the problems you identified, so I'll close this one now. Thanks again for your help.

**Closed as completed by ellbur** 2021-05-25 13:21 UTC

**Comment by AwesomeLemon** [comment] 2021-05-25 13:57
I see your point about the virtual keyboard. Well, good luck with these problems & thanks again for this program
